services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_container
        restart: unless-stopped
        ports:
            - "28018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin1234
        volumes:
            - mongodb_cont:/data/db
        networks:
            - mongo_network

volumes:
    mongodb_cont:

networks:
    mongo_network:
        name: mongo_network